### ISSUE TITLE
[🎹 Inside Test] Sometimes post trial mistakes animation only shows first note but doesn't audibly play it

### ISSUE THREAD

**Issue by giladbarnea** [idotavorslab/PYANO#38]
example:
https://mail.google.com/mail/u/0/#inbox/FMfcgxwCgCKbnlQnfCnGKDnjqknLjQKj?projector=1

## Todo
- [x] ~~shorten salamander mp3 file length~~ _<span style="color: orange">already as short as possible out of the box</span>_
- [ ] [update packages (tambien Piano wip branch)]
(https://github.com/tambien/Piano/compare/master..refactor-wip)
- [X] make userMidi Piano NOT load any samplers _(heisenbug/samplers)_
- [X] try awaiting Transport.start(), Piano.this._notes.start() and other async functions _(heisenbug/samplers)_
- [ ] shachar's idea (dummy note before actual first note)
- [ ] redesign so animationPiano.keyDown() and animation.markKey await each other and share the same thread
- [ ] cache as much as possible; play user trial not from new midi but from data; dont dispose sampler
- [ ] Use Node 12.x instead of 10.x

**Comment by ShacharGal** [comment]
still happens sometime. seen it only in error animations of acc error made in tempo mode. it doesn't necessarily imply it is not broader...

**Comment by ShacharGal** [comment]
it happens in acc pos-animations as well.
but not consistently... very strange

**Comment by giladbarnea** [comment]
Happens pretty consistently with the following config
[test_1.zip](https://github.com/idotavorslab/PYANO/files/3251952/test_1.zip)

**Comment by giladbarnea** [comment]
Probably has something to do with https://github.com/idotavorslab/PYANO/issues/86
